# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /home/linux1/recipes/iniconfig-feedstock/recipe, last modified Mon Jan 18 10:16:50 2021
# ------------------------------------------------

package:
    name: iniconfig
    version: 1.1.1
source:
    sha256: bc3af051d7d14b2ee5ef9969666def0cd1a000e121eaea580d4a313df4b37f32
    url: https://pypi.io/packages/source/i/iniconfig/iniconfig-1.1.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/linux1/recipes/ci/iniconfig_1610983019677/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . -vv
    string: pyhd3eb1b0_0
requirements:
    host:
        - _libgcc_mutex 0.1 anaconda_defaults
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.12.8 ha847dfd_0
        - certifi 2020.12.5 py37ha847dfd_0
        - ld_impl_linux-s390x 2.33.1 ha4e4b1c_1
        - libedit 3.1.20191231 h2a837d6_0
        - libffi 3.2.1 hd8db5ea_1007
        - libgcc-ng 9.3.0 hc647ab7_17
        - libgomp 9.3.0 hc647ab7_17
        - libstdcxx-ng 9.3.0 hc891710_17
        - ncurses 6.2 h2a837d6_0
        - openssl 1.1.1i h2a837d6_0
        - pip 20.3.3 py37ha847dfd_0
        - python 3.7.9 h08cc55f_0
        - readline 8.0 h2a837d6_0
        - setuptools 51.1.2 py37ha847dfd_4
        - setuptools-scm 5.0.1 pyhd3eb1b0_0
        - setuptools_scm 5.0.1 hd3eb1b0_0
        - sqlite 3.32.3 haa4ac92_0
        - tk 8.6.10 h2795051_1
        - wheel 0.36.2 pyhd3eb1b0_0
        - xz 5.2.5 h2a837d6_0
        - zlib 1.2.11 h2a837d6_4
    run:
        - python
test:
    commands:
        - pip check
    imports:
        - iniconfig
    requires:
        - pip
about:
    home: http://github.com/RonnyPfannschmidt/iniconfig
    license: MIT
    license_file: LICENSE
    summary: 'iniconfig: brain-dead simple config-ini parsing'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nicoddemus
