# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_34hd27z78h/clone/recipe, last modified Thu Nov  7 12:56:01 2024
# ------------------------------------------------

package:
  name: werkzeug
  version: 3.0.6
source:
  sha256: a8dd59d4de28ca70471a34cba79bed5f7ef2e036a76b3ab0835474246eb41f8d
  url: https://pypi.io/packages/source/W/Werkzeug/werkzeug-3.0.6.tar.gz
build:
  number: '0'
  script: /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_34hd27z78h/croot/werkzeug_1731005772104/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --no-build-isolation -v
  string: py312hecd8cb5_0
requirements:
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.9.24 hecd8cb5_0
    - expat 2.6.3 h6d0c2b6_0
    - flit-core 3.9.0 py312hee8aa70_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.15 h46256e1_0
    - pip 24.2 py312hecd8cb5_0
    - python 3.12.7 hcd54a6c_0
    - readline 8.2 hca72f7f_0
    - setuptools 75.1.0 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - markupsafe >=2.1.1
    - python >=3.12,<3.13.0a0
  run_constrained:
    - watchdog >=2.3
test:
  commands:
    - pip check
  imports:
    - werkzeug
    - werkzeug.debug
  requires:
    - pip
about:
  description: 'Werkzeug is a WSGI utility library for Python. It''s widely used and
    BSD licensed.

    '
  dev_url: https://github.com/pallets/werkzeug
  doc_url: https://werkzeug.palletsprojects.com/
  home: https://palletsprojects.com/p/werkzeug/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The comprehensive WSGI web application library.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 34657673-27f8-4d49-a686-00a6837c7ef8
  recipe-maintainers:
    - goanpeca
    - mcs07
  remote_url: git@github.com:AnacondaRecipes/werkzeug-feedstock.git
  sha: 72b04bca5df55645d691697f4932466f193dd6bf
