# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /Users/builder/cbouss/perseverance-python-buildout/aggregate/click-feedstock/recipe, last modified Sun Nov  5 19:41:49 2023
# ------------------------------------------------

package:
  name: click
  version: 8.1.7
source:
  sha256: ca9853ad459e787e2192211578cc907e7594e294c7ccc834310722b41b9ca6de
  url: https://pypi.io/packages/source/c/click/click-8.1.7.tar.gz
build:
  number: '0'
  script: /Users/builder/cbouss/perseverance-python-buildout/croot/click_1699239792454/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312hecd8cb5_0
requirements:
  host:
    - bzip2 1.0.8 h1de35cc_0
    - ca-certificates 2023.08.22 hecd8cb5_0
    - expat 2.5.0 hcec6c5f_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_0
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.12 hca72f7f_0
    - pip 23.3 py312hecd8cb5_0
    - python 3.12.0 hd58486a_0
    - readline 8.2 hca72f7f_0
    - setuptools 68.0.0 py312hecd8cb5_0
    - sqlite 3.41.2 h6c40b1e_0
    - tk 8.6.12 h5d9f67b_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.4.2 h6c40b1e_0
    - zlib 1.2.13 h4dc903c_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
  imports:
    - click
  requires:
    - pip
about:
  description: 'Click is a Python package for creating beautiful command line interfaces
    in a composable way

    with as little code as necessary. It''s the "Command Line Interface Creation Kit".

    It''s highly configurable but comes with sensible defaults out of the box.

    It aims to make the process of writing command line tools quick and fun

    while also preventing any frustration caused by the inability to implement an
    intended CLI API.

    '
  dev_url: https://github.com/pallets/click
  doc_url: https://click.palletsprojects.com
  home: https://palletsprojects.com/p/click/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python composable command line interface toolkit
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
    - xylar
