# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_f7bt4rtvu8/clone/recipe, last modified Fri May 24 01:48:59 2024
# ------------------------------------------------

package:
  name: itsdangerous
  version: 2.2.0
source:
  sha256: e0050c0b7da1eea53ffaf149c0cfbb5c6e2e2b69c4bef22c81fa6eb73e5f6173
  url: https://pypi.io/packages/source/i/itsdangerous/itsdangerous-2.2.0.tar.gz
build:
  number: '0'
  script: /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_f7bt4rtvu8/croot/itsdangerous_1716533350521/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py312hecd8cb5_0
requirements:
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.3.11 hecd8cb5_0
    - expat 2.6.2 hcec6c5f_0
    - flit-core 3.9.0 py312hee8aa70_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.13 hca72f7f_2
    - pip 24.0 py312hecd8cb5_0
    - python 3.12.3 hd58486a_1
    - readline 8.2 hca72f7f_0
    - setuptools 69.5.1 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.43.0 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest -v
  imports:
    - itsdangerous
  requires:
    - freezegun
    - pip
    - pytest
  source_files:
    - tests
about:
  description: 'Various helpers to pass data to untrusted environments and to get
    it

    back safe and sound. Data is cryptographically signed to ensure that a

    token has not been tampered with.


    It''s possible to customize how data is serialized. Data is compressed as

    needed. A timestamp can be added and verified automatically while

    loading a token.

    '
  dev_url: https://github.com/pallets/itsdangerous
  doc_url: https://itsdangerous.palletsprojects.com/
  home: https://github.com/pallets/itsdangerous
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Safely pass data to untrusted environments and back.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f765d9fe-fb14-4e42-b32f-dde1840cb2b7
  recipe-maintainers:
    - goanpeca
    - nicoddemus
    - williamjamir
  remote_url: git@github.com:AnacondaRecipes/itsdangerous-feedstock.git
  sha: 0c7fe61461ed891705717e5f3cfeeedcad66c5bd
