# This file created by conda-build 24.5.0
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_0bn8z9nupr/clone/recipe, last modified Fri May 24 05:17:53 2024
# ------------------------------------------------

package:
  name: flask
  version: 3.0.3
source:
  sha256: ceb27b0af3823ea2737928a4d99d125a06175b8512c445cbd9a9ce200ef76842
  url: https://pypi.io/packages/source/f/flask/flask-3.0.3.tar.gz
build:
  entry_points:
    - flask = flask.cli:main
  number: '0'
  script: /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_0bn8z9nupr/croot/flask_1716545880759/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py312hecd8cb5_0
requirements:
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.3.11 hecd8cb5_0
    - expat 2.6.2 hcec6c5f_0
    - flit-core 3.9.0 py312hee8aa70_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.13 hca72f7f_2
    - pip 24.0 py312hecd8cb5_0
    - python 3.12.3 hd58486a_1
    - readline 8.2 hca72f7f_0
    - setuptools 69.5.1 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.43.0 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - blinker >=1.6.2
    - click >=8.1.3
    - itsdangerous >=2.1.2
    - jinja2 >=3.1.2
    - python >=3.12,<3.13.0a0
    - werkzeug >=3.0.0
  run_constrained:
    - asgiref >=3.2
test:
  commands:
    - flask --help
    - pip check
    - pytest -vv
  imports:
    - flask
    - flask.json
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  description: 'Flask is a lightweight [WSGI](https://wsgi.readthedocs.io/) web application
    framework. It is designed

    to make getting started quick and easy, with the ability to scale up to

    complex applications. It began as a simple wrapper around [Werkzeug](https://werkzeug.palletsprojects.com/)

    and [Jinja](https://jinja.palletsprojects.com/) and has become one of the most
    popular Python web

    application frameworks.

    Flask offers suggestions, but doesn''t enforce any dependencies or

    project layout. It is up to the developer to choose the tools and

    libraries they want to use. There are many extensions provided by the

    community that make adding new functionality easy.

    '
  dev_url: https://github.com/pallets/flask/
  doc_url: https://flask.palletsprojects.com/
  home: https://palletsprojects.com/p/flask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A simple framework for building complex web applications.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 0b3376c6-577c-4cdc-8510-12a868717223
  recipe-maintainers:
    - goanpeca
    - marcelotrevisani
    - nehaljwani
    - ukaratay
    - xylar
  remote_url: git@github.com:AnacondaRecipes/flask-feedstock.git
  sha: 35fe1d4e0048ae18f229151816f2492b9c51f477
