# This file created by conda-build 24.3.0
# meta.yaml template originally from:
# /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_af6w2d9k11/clone/recipe, last modified Thu Jul  4 09:04:12 2024
# ------------------------------------------------

package:
  name: packaging
  version: '24.1'
source:
  sha256: 026ed72c8ed3fcce5bf8950572258698927fd1dbda10a5e981cdf0ac37f4f002
  url: https://pypi.io/packages/source/p/packaging/packaging-24.1.tar.gz
build:
  number: '0'
  script: /var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_af6w2d9k11/croot/packaging_1720101860461/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312hecd8cb5_0
requirements:
  host:
    - bzip2 1.0.8 h6c40b1e_6
    - ca-certificates 2024.3.11 hecd8cb5_0
    - expat 2.6.2 hcec6c5f_0
    - flit-core 3.9.0 py312hee8aa70_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.14 h46256e1_0
    - pip 24.0 py312hecd8cb5_0
    - python 3.12.4 hcd54a6c_1
    - readline 8.2 hca72f7f_0
    - setuptools 69.5.1 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.14 h4d00af3_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.43.0 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_1
    - zlib 1.2.13 h4b97444_1
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - pytest -v tests
  imports:
    - packaging
  requires:
    - pip
    - pretend
    - pytest >=6.2.0
  source_files:
    - tests
about:
  description: 'Reusable core utilities for various Python Packaging interoperability
    specifications.

    This library provides utilities that implement the interoperability specifications

    which have clearly one correct behaviour (eg: PEP 440) or benefit greatly from
    having

    a single shared implementation (eg: PEP 425).

    '
  dev_url: https://github.com/pypa/packaging
  doc_url: https://packaging.pypa.io
  home: https://github.com/pypa/packaging
  license: Apache-2.0 or BSD-2-Clause
  license_family: Apache
  license_file: LICENSE
  summary: Core utilities for Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: af2c1be7-4674-4f32-a2ee-fe8de31d513b
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - nicoddemus
  remote_url: git@github.com:AnacondaRecipes/packaging-feedstock.git
  sha: 18c297c4ebb42012d36079fa674673cbef80fa15
  skip-lints:
    - missing_wheel
