# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_48rgxrmler/clone/recipe, last modified Tue Apr 30 16:11:32 2024
# ------------------------------------------------

package:
  name: pycosat
  version: 0.6.6
source:
  sha256: b0014986321e77a36d8fe24827698aae076500c817133a700608bd677b77a998
  url: https://github.com/conda/pycosat/archive/0.6.6.tar.gz
build:
  number: '1'
  script: /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_48rgxrmler/croot/pycosat_1714511500164/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv
  string: py312h6c40b1e_1
requirements:
  build:
    - bzip2 1.0.8 h6c40b1e_5
    - ca-certificates 2024.3.11 hecd8cb5_0
    - cctools_osx-64 949.0.1 hc7db93f_25
    - clang 14.0.6 hecd8cb5_1
    - clang-14 14.0.6 default_hd95374b_1
    - clang_osx-64 14.0.6 hb1e4b1b_0
    - clangxx 14.0.6 default_hd95374b_1
    - compiler-rt 14.0.6 hda8b6b8_0
    - compiler-rt_osx-64 14.0.6 h8d5cb93_0
    - expat 2.6.2 hcec6c5f_0
    - ld64_osx-64 530 h70f3046_25
    - ldid 2.1.5 hc58f1be_3
    - libclang-cpp14 14.0.6 default_hd95374b_1
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - libllvm14 14.0.6 h91fad77_3
    - llvm-tools 14.0.6 he0576d7_3
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.13 hca72f7f_0
    - pip 23.3.1 py312hecd8cb5_0
    - python 3.12.3 hd58486a_0
    - readline 8.2 hca72f7f_0
    - setuptools 68.2.2 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tapi 1000.10.8 ha1b3eb9_0
    - tk 8.6.12 h5d9f67b_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.41.2 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_0
    - zlib 1.2.13 h4dc903c_0
  host:
    - bzip2 1.0.8 h6c40b1e_5
    - ca-certificates 2024.3.11 hecd8cb5_0
    - expat 2.6.2 hcec6c5f_0
    - libcxx 14.0.6 h9765a3e_0
    - libffi 3.4.4 hecd8cb5_1
    - ncurses 6.4 hcec6c5f_0
    - openssl 3.0.13 hca72f7f_0
    - pip 23.3.1 py312hecd8cb5_0
    - python 3.12.3 hd58486a_0
    - readline 8.2 hca72f7f_0
    - setuptools 68.2.2 py312hecd8cb5_0
    - sqlite 3.45.3 h6c40b1e_0
    - tk 8.6.12 h5d9f67b_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.41.2 py312hecd8cb5_0
    - xz 5.4.6 h6c40b1e_0
    - zlib 1.2.13 h4dc903c_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
    - python test_package.py "0.6.6"
  files:
    - qg3-08.cnf
    - sudoku.py
    - test_package.py
    - uf20-098.cnf
  imports:
    - pycosat
  requires:
    - pip
about:
  description: 'PicoSAT is a popular SAT solver written by Armin Biere in pure C.
    This

    package provides efficient Python bindings to picosat on the C level, i.e.

    when importing pycosat, the picosat solver becomes part of the Python

    process itself.

    '
  dev_url: https://github.com/conda/pycosat
  doc_source_url: https://github.com/conda/pycosat/blob/master/README.rst
  doc_url: https://pypi.org/project/pycosat/
  home: https://github.com/conda/pycosat
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  license_url: https://github.com/conda/pycosat/blob/0.6.6/LICENSE
  summary: Bindings to picosat (a SAT solver)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 48a387fd-cdb6-4cf9-b723-7f966d3b0aff
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - nehaljwani
    - pelson
  remote_url: git@github.com:AnacondaRecipes/pycosat-feedstock.git
  sha: dc25cc6e60242b93fedcbf494807e03cf55910f7
